name: Build Windows EXE and Installer

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: pwsh

      - name: PyInstaller (one-folder)
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "JohnsElbow" backend.py
        shell: pwsh

      - name: Upload app (dist exe)
        uses: actions/upload-artifact@v4
        with:
          name: JohnsElbow-exe
          path: dist/JohnsElbow.exe

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: pwsh

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: JohnsElbow-Installer
          path: JohnsElbow-Setup.exe
