name: Build Windows EXE and Installer

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstaller (one-folder)
        run: |
          pyinstaller --noconfirm --windowed --name "GestureKeys" backend.py
        shell: pwsh

      - name: Upload app (dist folder)
        uses: actions/upload-artifact@v4
        with:
          name: GestureKeys-dist
          path: dist/GestureKeys/

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        shell: pwsh

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: GestureKeys-Installer
          path: GestureKeys-Setup.exe
